config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'

  resources :users, except: [:new] do
   resources :recipes, only: [:show]
  end

  resources :recipes, except: [:show] do
    get 'edit_instructions', to: 'recipes#edit_instructions'
    get 'edit_ingredients', to: 'recipes#edit_ingredients'
  end

  get 'login', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :body, presence: true
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe

  validates :body, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  MAXIMUM_LENGTH = 150

  belongs_to :user

  has_many :instructions, dependent: :destroy
  has_many :ingredients, dependent: :destroy

  accepts_nested_attributes_for :ingredients, :instructions, allow_destroy: true

  validates :description, presence: true, length: {maximum: MAXIMUM_LENGTH}
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  PASSWORD_FORMAT = /\A[A-Z]+(\.[A-Z]+)?[0-9]*\z/i
  MINIMUM_LENGTH = 8

  has_many :recipes, dependent: :destroy

  before_save :name_capitalize
  before_save :email_to_downcase

  has_secure_password
  
  validates :full_name, presence: true, length: {minimum: MINIMUM_LENGTH}
  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: {case_sensitive: true}, presence: true, format: {with: EMAIL_FORMAT }
  validates :password, presence: true, length: {minimum: MINIMUM_LENGTH},
            format: {with: PASSWORD_FORMAT, :message => 'must contains and starts with letters(numbers can be used last!)'}

  private

  def name_capitalize
    self.full_name = full_name.downcase.titleize
    self.first_name = first_name.downcase.capitalize
    self.last_name = last_name.downcase.capitalize
  end

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :require_login

  private

  def require_login
    unless current_user_present?
      flash[:danger] = 'Please log in to continue!'
      redirect_to login_path
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :find_recipe_with_recipe_id, only: [:edit_ingredients, :edit_instructions]
  before_action :is_user_valid?, except: [:index, :show, :new, :create]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
    6.times { @recipe.ingredients.build }
    6.times { @recipe.instructions.build }
  end

  def create
    @recipe = Recipe.new(recipes_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to user_recipe_path(@recipe.user, @recipe)
    else
      render :new
    end
  end

  def edit
    @recipe.ingredients.find_all
    @recipe.instructions.find_all
  end

  def edit_instructions
    @recipe.instructions.find_all
  end

  def edit_ingredients
    @recipe.ingredients.find_all
  end

  def update
    @recipe.update_attributes(recipes_params)
    if @recipe.save
      redirect_to user_recipe_path(@recipe.user, @recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  private

  def recipes_params
    params.require(:recipe).permit(:title, :description,
    ingredients_attributes: [:id, :recipe_id, :body, :_destroy],
    instructions_attributes: [:id, :recipe_id, :body, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def find_recipe_with_recipe_id
    @recipe = Recipe.find(params[:recipe_id])
  end

  def is_user_valid?
    unless equal_with_current_user(@recipe.user)
      flash[:warning] = 'Wrong user!'
      redirect_to user_path(@current_user) and return
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create]

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = 'Successfully logged in!'
      redirect_to user
    else
      flash[:danger] = 'Invalid combination of email or password!'
      redirect_to login_path
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login
  before_action :is_user_present?, except: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def is_user_present?
    if current_user_present?
      flash[:danger] = 'Already logged in!'
      redirect_to user_path(@current_user) and return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user_present?
    current_user.present?
  end

  def equal_with_current_user(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'components/nav_bar'%>
    <%= render 'components/flash'%>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<div class="row">
  <div class="col-sm-6 ml-5 ">
    <div class="container mt-5">
      <div class=" card rounded-circle recipe-color ">
        <div class=" text-center">
          <% unless local_assigns[:show] %>
            <%= link_to "Show", user_recipe_path(recipe.user, recipe), class: "btn recipe-color ml-2 mt-3 text-white font-italic"%>
            <% if equal_with_current_user(recipe.user) %>
              <%= link_to "Edit cocktail", edit_recipe_path(recipe), class: "btn recipe-color ml-2 text-white font-italic" %>
              <%= link_to "Delete", recipe_path(recipe), class: "btn recipe-color mt-3 ml-2 text-white font-italic",
              method: :delete, data: { confirm: 'Are you sure you want to delete this cocktail recipe?'}%>
            <% end%>
          <% else %>
            <%= link_to "Back", root_path, class: "btn recipe-color mt-2 text-white font-italic"%>
          <% end %>
        </div>
        <div class="card-body text-center text-white font-italic"">
          <h2><strong><%= recipe.title %></strong></h2>
        </div>
        <div class="card-body text-center text-white mb-3 font-italic">
          <%= recipe.description %>
        </div>
        <div class="card-body text-white text-center font-italic">
          <strong>Created by: <%=link_to "#{recipe.user.full_name}", user_path(recipe.user), class: 'text-warning' %></strong>
          <strong><%=time_ago_in_words(recipe.created_at) %> ago</strong>
        </div>
      </div>
    </div>
  </div>
  <div class="card recipe-faded mt-5 ml-4 card-width">
    <div class="card-body text-warning">
      <div class="card-title font-italic mb-5">
        <h5>Ingredients needed for preparing</h5>
      </div>
      <% recipe.ingredients.each do |ingredient| %>
        <ul class='font-italic'>
          <li>
            <%= ingredient.body %>
          </li>
        </ul>
      <% end %>
    </div>
    <div class='card-footer'>
      <% if equal_with_current_user(recipe.user) %>
        <%= link_to "Edit/Delete ingredients", recipe_edit_ingredients_path(recipe), class: 'text-warning font-italic'%>
      <% end %>
    </div>
  </div>
  <div class="card text-white recipe-color mt-5 ml-5 card-width">
    <div class="card-header font-italic">
      <h5>Instructions for preparing</h5>
    </div>
    <div class="card-body">
      <% recipe.instructions.each do |instruction| %>
        <ul class="mb-0 font-italic">
          <li>
            <%= instruction.body %>
          </li>
        </ul>
      <% end %>
    </div>
    <div class='card-footer recipe-color'>
      <% if equal_with_current_user(recipe.user) %>
        <%= link_to "Edit/Delete instructions", recipe_edit_instructions_path(recipe), class: 'text-white font-italic'%>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container mt-5">
 <%= render "components/form",
 model: @recipe,
 button_name: 'Update',
 heading: 'Edit cocktail',
 nested_form: true %>
</div>

app/views/recipes/edit_ingredients.html.erb
<div class="container fluid">
  <h1 class="h2 mt-5 font-weight-8px text-white text-center font-italic">Edit ingredients</h1>
  <div class="container mt-5 col-sm-15 mr-5 ">
    <%= form_with model: @recipe, local: true do |form| %>
      <%= render "components/ingredients", form: form %>
      <%= form.submit 'Update ingredients', class: "btn btn-lg btn-block recipe-faded font-italic" %>
    <% end %>
  </div>
</div>

app/views/recipes/edit_instructions.html.erb
<div class="container fluid">
  <h1 class="h2 mt-5 font-weight-8px text-white text-center font-italic">Edit instructions</h1>
  <div class="container mt-5 col-sm-15 mr-5 ">
    <%= form_with model: @recipe, local: true do |form| %>
      <%= render "components/instructions", form: form %>
      <%= form.submit 'Update instructions', class: "btn btn-lg btn-block recipe-faded font-italic" %>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<h1 class="text-center text-white recipe-color font-italic"><strong>Cocktail recipes</strong></h1>
<% @recipes.each do |recipe|%>
  <div class="ml-5 ">
    <%= render 'recipe', recipe: recipe %>
  </div>
<%end %>

app/views/recipes/new.html.erb
<div class="container mt-5">
 <%= render "components/form",
 model: @recipe,
 button_name: 'Save',
 heading: 'New cocktail',
 nested_form: true %>
</div>

app/views/recipes/show.html.erb
<div class="ml-5 center">
  <%= render 'recipe',
  recipe: @recipe,
  show: true %>
</div>

app/views/users/new.html.erb
<div class='container mt-5'>
  <div class="row text-center">
    <div class="col-sm-8">
      <body class="text-center bg-light">
        <%= form_with url: login_path, scope: :session, local: true do |form| %>
          <%= image_tag 'cocktail1.jpg', width: '100px', class: "rounded-circle" %>
          <div class='container-fluid'>
            <%= form.label :full_name, class: "sr-only" %>
            <%= form.text_field :full_name, class: "form-control recipe-color mt-4", placeholder: "Full name" %>
            <%= form.label :email, class: "sr-only" %>
            <%= form.email_field :email, class: "form-control recipe-color mt-4", placeholder: "Email address" %>
            <%= form.label :password, class: "sr-only" %>
            <%= form.password_field :password, class: "form-control recipe-color mt-4", placeholder: "Password" %>
            <%= form.submit "Log in", class: "btn btn-lg recipe-color btn-block mt-5 font-italic"%>
          </div>
        <%end%>
      </body>
    </div>
    <div class="col-sm-4">
      <%= render 'components/errors', model: @user %>
      <%= render 'components/form', model: @user , button_name: "Sign up", heading: "Sign up", new: true %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class=" mt-5">
  <div class='container '>
    <div class=" card rounded-circle recipe-color">
      <div class="card-body text-center text-white mt-5">
        <h3><strong><%= @user.full_name %>'s cocktail recipes</strong></h3>
      </div>
      <div class="card-body text-center">
        <%= @user.email %>
      </div>
      <div class="card-body text-center">
        <%= link_to "Back", root_path, class: "nav-link text-white"%>
      </div>
    </div>
  </div>
</div>
<% @user.recipes.each do |recipe|%>
  <%= render 'recipes/recipe', recipe: recipe %>
<%end %>